# -*- coding: utf-8 -*-
"""Emitrr_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cqAH8fUnmARlXqGasZpp6FBU8FbZFUkZ
"""

Input_Text = '''> **Physician:** *Good morning, Ms. Jones. How are you feeling today?*
>
>
> **Patient:** *Good morning, doctor. I’m doing better, but I still have some discomfort now and then.*
>
> **Physician:** *I understand you were in a car accident last September. Can you walk me through what happened?*
>
> **Patient:** *Yes, it was on September 1st, around 12:30 in the afternoon. I was driving from Cheadle Hulme to Manchester when I had to stop in traffic. Out of nowhere, another car hit me from behind, which pushed my car into the one in front.*
>
> **Physician:** *That sounds like a strong impact. Were you wearing your seatbelt?*
>
> **Patient:** *Yes, I always do.*
>
> **Physician:** *What did you feel immediately after the accident?*
>
> **Patient:** *At first, I was just shocked. But then I realized I had hit my head on the steering wheel, and I could feel pain in my neck and back almost right away.*
>
> **Physician:** *Did you seek medical attention at that time?*
>
> **Patient:** *Yes, I went to Moss Bank Accident and Emergency. They checked me over and said it was a whiplash injury, but they didn’t do any X-rays. They just gave me some advice and sent me home.*
>
> **Physician:** *How did things progress after that?*
>
> **Patient:** *The first four weeks were rough. My neck and back pain were really bad—I had trouble sleeping and had to take painkillers regularly. It started improving after that, but I had to go through ten sessions of physiotherapy to help with the stiffness and discomfort.*
>
> **Physician:** *That makes sense. Are you still experiencing pain now?*
>
> **Patient:** *It’s not constant, but I do get occasional backaches. It’s nothing like before, though.*
>
> **Physician:** *That’s good to hear. Have you noticed any other effects, like anxiety while driving or difficulty concentrating?*
>
> **Patient:** *No, nothing like that. I don’t feel nervous driving, and I haven’t had any emotional issues from the accident.*
>
> **Physician:** *And how has this impacted your daily life? Work, hobbies, anything like that?*
>
> **Patient:** *I had to take a week off work, but after that, I was back to my usual routine. It hasn’t really stopped me from doing anything.*
>
> **Physician:** *That’s encouraging. Let’s go ahead and do a physical examination to check your mobility and any lingering pain.*
>
> [**Physical Examination Conducted**]
>
> **Physician:** *Everything looks good. Your neck and back have a full range of movement, and there’s no tenderness or signs of lasting damage. Your muscles and spine seem to be in good condition.*
>
> **Patient:** *That’s a relief!*
>
> **Physician:** *Yes, your recovery so far has been quite positive. Given your progress, I’d expect you to make a full recovery within six months of the accident. There are no signs of long-term damage or degeneration.*
>
> **Patient:** *That’s great to hear. So, I don’t need to worry about this affecting me in the future?*
>
> **Physician:** *That’s right. I don’t foresee any long-term impact on your work or daily life. If anything changes or you experience worsening symptoms, you can always come back for a follow-up. But at this point, you’re on track for a full recovery.*
>
> **Patient:** *Thank you, doctor. I appreciate it.*
>
> **Physician:** *You’re very welcome, Ms. Jones. Take care, and don’t hesitate to reach out if you need anything.*
>'''

import re
def clean_text(text_lines):
  cleaned_lines = []
  for line in text_lines:
    cleaned_line = re.sub(r'[>*]', '', line)
    cleaned_line = re.sub(r'\s+', ' ', cleaned_line).strip()
    cleaned_lines.append(cleaned_line)
  return cleaned_lines

clean_text(Input_Text.split('\n'))

new_text = "".join(clean_text(Input_Text.split('\n')))
new_text

import spacy
nlp = spacy.load("en_core_web_sm")
doc = nlp(new_text)
for ent in doc.ents:
    print(ent.text, ent.label_)

sentences = list(doc.sents)

sentences

dialogue_lines = clean_text(Input_Text.split('\n'))
patient_sentences = []
for line in dialogue_lines:
    if line.strip().startswith('Patient:'):
        cleaned_sentence = line.replace('Patient:', '', 1).strip()
        if cleaned_sentence:
            patient_sentences.append(cleaned_sentence)
print(patient_sentences)

patient_sentences = [sentence for sentence in patient_sentences if sentence.strip()]
print(patient_sentences)

from transformers import pipeline

# Initialize the zero-shot classification pipeline
classifier = pipeline("zero-shot-classification")

# Define candidate labels for sentiment and intent
sentiment_labels = ["Anxious", "Neutral", "Reassured"]
intent_labels = ["Seeking reassurance", "Reporting symptoms", "Expressing concern", "Providing information"]

patient_analysis_results = []

for sentence in patient_sentences:
    # Classify sentiment
    sentiment_result = classifier(sentence, candidate_labels=sentiment_labels, multi_label=False)
    predicted_sentiment = sentiment_result['labels'][0]

    # Classify intent
    intent_result = classifier(sentence, candidate_labels=intent_labels, multi_label=False)
    predicted_intent = intent_result['labels'][0]

    patient_analysis_results.append({
        "sentence": sentence,
        "sentiment": predicted_sentiment,
        "intent": predicted_intent
    })

# Print the results for review
for result in patient_analysis_results:
    print(f"Sentence: {result['sentence']}")
    print(f"Sentiment: {result['sentiment']}")
    print(f"Intent: {result['intent']}")
    print("---------------------")

import pandas as pd
df_patient_analysis = pd.DataFrame(patient_analysis_results)

print(df_patient_analysis.head())
print(df_patient_analysis['sentiment'].value_counts())
print(df_patient_analysis['intent'].value_counts())

from transformers import pipeline
classifier = pipeline("zero-shot-classification")
soap_labels = ["Subjective", "Objective", "Assessment", "Plan"]
print("SOAP labels defined.")

soap_analysis_results = []

for sentence in dialogue_lines:
    if not sentence.strip():
        continue

    soap_result = classifier(sentence, candidate_labels=soap_labels, multi_label=False)
    predicted_soap_category = soap_result['labels'][0]

    soap_analysis_results.append({
        "sentence": sentence,
        "soap_category": predicted_soap_category
    })

# Print the results for review
for result in soap_analysis_results:
    print(f"Sentence: {result['sentence']}")
    print(f"SOAP Category: {result['soap_category']}")
    print("---------------------")

soap_note = {'Subjective': [], 'Objective': [], 'Assessment': [], 'Plan': []}

for item in soap_analysis_results:
    category = item['soap_category']
    sentence = item['sentence']
    if category in soap_note:
        soap_note[category].append(sentence)

# Print the structured SOAP note
for category, sentences_list in soap_note.items():
    print(f"\n{category}:")
    for sentence in sentences_list:
        print(f"- {sentence}")